import { auth } from "@/lib/auth"
import { NextResponse } from "next/server"
import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"

export async function POST(req: Request) {
  try {
    const session = await auth()
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await req.json()
    const { title, period, sections } = body

    // Create PDF Document
    const doc = new jsPDF()

    // Header
    doc.setFontSize(22)
    doc.text("GrowzzyOS Intelligence Brief", 14, 22)

    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text(`Generated: ${new Date().toLocaleDateString()} | Period: ${period}`, 14, 30)
    doc.text(`Prepared for: ${session.user.name || session.user.email}`, 14, 35)

    let yPos = 45

    // Overview Section
    if (sections.overview) {
      doc.setFillColor(31, 87, 245) // Primary Blue
      doc.rect(14, yPos, 182, 8, 'F')
      doc.setTextColor(255)
      doc.setFontSize(12)
      doc.text("Executive Summary", 18, yPos + 5.5)
      yPos += 15

      doc.setTextColor(0)
      doc.setFontSize(10)
      doc.text("Performance Metrics:", 14, yPos)
      yPos += 5

      autoTable(doc, {
        startY: yPos,
        head: [['Metric', 'Value', 'YoY Change']],
        body: [
          ['Total Revenue', '$142,590', '+12.4%'],
          ['Ad Spend', '$38,200', '+5.1%'],
          ['ROAS', '3.73x', '+8.2%'],
          ['Conversion Rate', '2.8%', '+0.4%']
        ],
        theme: 'grid',
        headStyles: { fillColor: [240, 240, 240], textColor: [50, 50, 50], fontStyle: 'bold' }
      })
      yPos = (doc as any).lastAutoTable.finalY + 15
    }

    // Channels
    if (sections.channels) {
      doc.setFillColor(31, 87, 245)
      doc.rect(14, yPos, 182, 8, 'F')
      doc.setTextColor(255)
      doc.setFontSize(12)
      doc.text("Channel Breakdown", 18, yPos + 5.5)
      yPos += 15

      autoTable(doc, {
        startY: yPos,
        head: [['Channel', 'Spend', 'Revenue', 'ROAS']],
        body: [
          ['Meta Ads', '$15,200', '$58,400', '3.84x'],
          ['Google Search', '$12,100', '$49,200', '4.06x'],
          ['TikTok', '$8,500', '$18,700', '2.20x']
        ],
        theme: 'striped'
      })
      yPos = (doc as any).lastAutoTable.finalY + 15
    }

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text("Generated by GrowzzyOS Enterprise Report Engine", 14, 285)

    // Return Buffer
    const pdfBuffer = doc.output('arraybuffer')

    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${title.replace(/\s+/g, '_')}.pdf"`
      }
    })

  } catch (e: any) {
    console.error("PDF Generation Error", e)
    return NextResponse.json({ error: e.message || "Failed to generate report" }, { status: 500 })
  }
}
