import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF to support autotable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface ReportData {
  title: string;
  dateRange: string;
  executiveSummary: {
    wins: string[];
    concerns: string[];
  };
  kpi: {
    totalSpend: number;
    totalRevenue: number;
    roas: number;
    conversions: number;
  };
  campaigns: Array<{
    name: string;
    platform: string;
    spend: number;
    revenue: number;
    roas: number;
    conversions: number;
    status: string;
  }>;
  platformBreakdown: Array<{
    platform: string;
    spend: number;
    revenue: number;
    roas: number;
  }>;
  aiInsights: string[];
}

export async function generatePDFReport(data: ReportData): Promise<Blob> {
  const doc = new jsPDF();
  
  // Set font
  doc.setFont('helvetica');
  
  // Header
  doc.setFontSize(20);
  doc.text(data.title, 20, 20);
  
  doc.setFontSize(12);
  doc.text(`Date Range: ${data.dateRange}`, 20, 30);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 40);
  
  let yPosition = 60;
  
  // Executive Summary
  doc.setFontSize(16);
  doc.text('Executive Summary', 20, yPosition);
  yPosition += 15;
  
  doc.setFontSize(12);
  doc.text('Key Wins:', 20, yPosition);
  yPosition += 10;
  
  data.executiveSummary.wins.forEach((win, index) => {
    doc.text(`• ${win}`, 25, yPosition);
    yPosition += 8;
  });
  
  yPosition += 10;
  doc.text('Areas of Concern:', 20, yPosition);
  yPosition += 10;
  
  data.executiveSummary.concerns.forEach((concern, index) => {
    doc.text(`• ${concern}`, 25, yPosition);
    yPosition += 8;
  });
  
  // KPI Dashboard
  yPosition += 15;
  doc.setFontSize(16);
  doc.text('KPI Dashboard', 20, yPosition);
  yPosition += 15;
  
  doc.setFontSize(12);
  doc.text(`Total Spend: ₹${data.kpi.totalSpend.toLocaleString()}`, 20, yPosition);
  yPosition += 10;
  doc.text(`Total Revenue: ₹${data.kpi.totalRevenue.toLocaleString()}`, 20, yPosition);
  yPosition += 10;
  doc.text(`Overall ROAS: ${data.kpi.roas}x`, 20, yPosition);
  yPosition += 10;
  doc.text(`Total Conversions: ${data.kpi.conversions}`, 20, yPosition);
  
  // Campaign Performance Table
  yPosition += 20;
  doc.setFontSize(16);
  doc.text('Campaign Performance', 20, yPosition);
  yPosition += 15;
  
  // Add table
  doc.autoTable({
    head: [['Campaign', 'Platform', 'Spend', 'Revenue', 'ROAS', 'Conversions', 'Status']],
    body: data.campaigns.map(campaign => [
      campaign.name,
      campaign.platform,
      `₹${campaign.spend.toLocaleString()}`,
      `₹${campaign.revenue.toLocaleString()}`,
      `${campaign.roas}x`,
      campaign.conversions.toString(),
      campaign.status
    ]),
    startY: yPosition,
    theme: 'grid',
    styles: { fontSize: 10 },
    headStyles: { fillColor: [0, 0, 0] }
  });
  
  // Platform Breakdown
  yPosition = (doc as any).lastAutoTable.finalY + 20;
  doc.setFontSize(16);
  doc.text('Platform Breakdown', 20, yPosition);
  yPosition += 15;
  
  doc.autoTable({
    head: [['Platform', 'Spend', 'Revenue', 'ROAS']],
    body: data.platformBreakdown.map(platform => [
      platform.platform,
      `₹${platform.spend.toLocaleString()}`,
      `₹${platform.revenue.toLocaleString()}`,
      `${platform.roas}x`
    ]),
    startY: yPosition,
    theme: 'grid',
    styles: { fontSize: 10 },
    headStyles: { fillColor: [0, 0, 0] }
  });
  
  // AI Insights
  yPosition = (doc as any).lastAutoTable.finalY + 20;
  doc.setFontSize(16);
  doc.text('AI Recommendations', 20, yPosition);
  yPosition += 15;
  
  doc.setFontSize(12);
  data.aiInsights.forEach((insight, index) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    const lines = doc.splitTextToSize(`${index + 1}. ${insight}`, 170);
    lines.forEach((line: string) => {
      doc.text(line, 20, yPosition);
      yPosition += 8;
    });
    yPosition += 5;
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(`Page ${i} of ${pageCount}`, 20, 280);
    doc.text('Generated by GrowzzyOS', 170, 280);
  }
  
  return new Blob([doc.output('blob')], { type: 'application/pdf' });
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
